Repository LibreSprite/LibreSprite, pull requests merged in 2021-11, with the labels that each got.

#296 Remove V8 pointers compression on 32-bit architectures
  CMakeLists.txt
Labels: bugfix, build

#299 Update required MacOS version to 11.0
  INSTALL.md
Labels: documentation, OS: Mac

#306 Deliver submodules too on every release
  .github/workflows/submodules-CD.yml
Labels: bugfix, build

#309 Fixes bug that prevents compiling on mac.
  src/ui/manager.cpp
Labels: bugfix, OS: Mac

#313 Macro for displaying package and version together
  src/app/app.cpp
  src/app/app_options.cpp
  src/app/commands/cmd_about.cpp
  src/app/log.cpp
  src/app/send_crash.cpp
  src/app/shell.cpp
  src/config.h
Labels: code quality
