Repository LibreSprite/LibreSprite, pull requests merged in 2021-10, with the labels that each got.

#266 Further improvements to the devconsole
  src/app/script/api/console_script.cpp
  src/app/ui/devconsole_view.cpp
  src/app/ui/devconsole_view.h
Labels: scripting

#262 Ensure task results are delivered in the correct order
  src/app/res/resources_loader.cpp
  src/app/task_manager.h
Labels: bugfix

#272 Fix minimizing window
  src/she/sdl2/sdl2_display.cpp
Labels: bugfix

#270 Change the window icon
  src/app/modules/gui.cpp
  src/she/display.h
  src/she/sdl2/sdl2_display.cpp
  src/she/sdl2/sdl2_display.h
Labels: bugfix

#268 Allow reading/writing all of an image's pixels at once
  src/app/script/api/image_script.cpp
Labels: scripting

#269 Allow scripts to alter a sprite's palette
  src/app/CMakeLists.txt
  src/app/script/api/palette_script.cpp
  src/app/script/api/sprite_script.cpp
Labels: scripting

#259 Compile release builds with -O2 and debug builds with -Og
  CMakeLists.txt
  src/allegro/CMakeLists.txt
  src/app/CMakeLists.txt
  src/script/CMakeLists.txt
  src/she/CMakeLists.txt
  src/ui/CMakeLists.txt
Labels: build

#274 Prevent unicode text from interfering with shortcut input
  src/she/sdl2/she.cpp
Labels: bugfix

#279 Pressing "Esc" closes the layer properties window
  src/app/commands/cmd_layer_properties.cpp
Labels: enhancement

#275 Create code analysis
  .github/workflows/codeql-analysis.yml
Labels: code quality
