Repository LibreSprite/LibreSprite, pull requests merged in 2021-09, with the labels that each got.

#183 Refactor scripting
  src/CMakeLists.txt
  src/app/CMakeLists.txt
  src/app/app.cpp
  src/app/commands/cmd_run_script.cpp
  src/app/script/api/app_script.cpp
  src/app/script/api/cel_script.cpp
  src/app/script/api/colormode_script.cpp
  src/app/script/api/console_script.cpp
  src/app/script/api/document_script.cpp
  src/app/script/api/image_script.cpp
  src/app/script/api/layer_script.cpp
  src/app/script/api/pixelcolor_script.cpp
  src/app/script/api/selection_script.cpp
  src/app/script/api/sprite_script.cpp
  src/app/script/app_object.cpp
  src/app/script/app_object.h
  src/app/script/app_scripting.cpp
  src/app/script/app_scripting.h
  src/app/script/console_delegate.cpp
  src/app/script/console_object.cpp
  src/app/script/console_object.h
  src/app/script/image_class.cpp
  src/app/script/image_class.h
  src/app/script/image_wrap.cpp
  src/app/script/image_wrap.h
  src/app/script/pixel_color.h
  src/app/script/script_menu.h
  src/app/script/selection_class.h
  src/app/script/sprite_class.cpp
  src/app/script/sprite_class.h
  src/app/script/sprite_wrap.cpp
  src/app/script/sprite_wrap.h
  src/app/shell.cpp
  src/app/shell.h
  src/app/ui/devconsole_view.cpp
  src/app/ui/devconsole_view.h
  src/base/injection.h
  src/script/CMakeLists.txt
  src/script/cout_delegate.cpp
  src/script/duktape/engine.cpp
  src/script/engine.cpp
  src/script/engine.h
  src/script/engine_delegate.h
  src/script/function.h
  src/script/script_object.h
  src/script/value.h
Labels: code quality, scripting

#195 Remove unused iff library
  src/README.md
  src/iff/LICENSE.txt
  src/iff/README.md
Labels: documentation

#199 she: Remove DisplayHandle
  src/she/display.h
  src/she/display_handle.h
  src/she/skia/skia_display.cpp
  src/she/skia/skia_display.h
Labels: code quality

#201 README: remove IRC and update Matrix link (space instead of room)
  README.md
Labels: documentation

#138 Move icons to proper directory
  desktop/icons/hicolor/16x16/apps/libresprite.png
  desktop/icons/hicolor/32x32/apps/libresprite.png
  desktop/icons/hicolor/48x48/apps/libresprite.png
  desktop/icons/hicolor/64x64/apps/libresprite.png
Labels: code quality

#203 Update INSTALL.md
  INSTALL.md
Labels: documentation

#204 Fix compilation error on debug builds
  src/app/app_menus.cpp
Labels: bugfix

#198 CMake cleanup
  CMakeLists.txt
  third_party/CMakeLists.txt
Labels: code quality

#193 base: Fix issues with musl libc
  src/base/fs_unix.h
  src/base/thread.cpp
Labels: bugfix

#192 Document scripting api
  src/app/console.cpp
  src/app/script/api/app_script.cpp
  src/app/script/api/image_script.cpp
  src/app/script/api/layer_script.cpp
  src/app/script/api/pixelcolor_script.cpp
  src/app/script/api/sprite_script.cpp
  src/script/script_object.h
Labels: enhancement, feature, documentation

#202 Add sourcehut build manifests
  .builds/alpine.yml
  .builds/arch.yml
  .builds/debian.yml
Labels: build

#208 Split PaletteListBox into two classes
  src/app/ui/palette_listbox.cpp
  src/app/ui/palette_listbox.h
  src/app/ui/palette_popup.h
Labels: code quality, feature

#212 Implement safe_ptr for safely accessing unowned objects
  src/base/safe_ptr.h
Labels: code quality

#207 Export pertag
  data/pref.xml
  data/widgets/export_sprite_sheet.xml
  src/app/commands/cmd_export_sprite_sheet.cpp
  src/app/document_exporter.cpp
  src/app/document_exporter.h
Labels: feature, import/export

#215 SDL2 backend
  CMakeLists.txt
  src/she/CMakeLists.txt
  src/she/sdl2/sdl2_display.cpp
  src/she/sdl2/sdl2_display.h
  src/she/sdl2/sdl2_surface.cpp
  src/she/sdl2/sdl2_surface.h
  src/she/sdl2/she.cpp
Labels: feature

#213 General scripting improvements
  src/app/commands/cmd_run_script.cpp
  src/app/console.cpp
  src/app/script/api/console_script.cpp
  src/app/script/app_scripting.cpp
  src/app/script/app_scripting.h
  src/base/injection.h
  src/script/duktape/engine.cpp
  src/script/engine.h
  src/script/function.h
  src/script/value.h
Labels: enhancement, scripting

#221 Add curl and sdl2 as dependencies
  .github/workflows/cmake.yml
  INSTALL.md
Labels: documentation

#222 Remove Travis and sourcehut CI
  .builds/alpine.yml
  .builds/arch.yml
  .builds/debian.yml
  .travis.yml
Labels: code quality

#223 Implementation of checked drawing mode for marching ants
  src/she/sdl2/sdl2_surface.cpp
Labels: bugfix

#219 Bump language version from C++11 to C++14
  CMakeLists.txt
  INSTALL.md
  src/CMakeLists.txt
  src/app/CMakeLists.txt
  src/script/CMakeLists.txt
Labels: enhancement

#231 Fix SDL2 compilation on Windows
  CMakeLists.txt
  cmake/FindSDL2.cmake
  cmake/FindSDL2_IMAGE.cmake
  src/she/CMakeLists.txt
Labels: bugfix, OS: Windows

#227 Send a mouseup event after a doubleclick event
  src/she/sdl2/she.cpp
Labels: bugfix

#234 Use PkgConfig if it has been found, fallback to previous behavior
  cmake/FindSDL2.cmake
  cmake/FindSDL2_IMAGE.cmake
  src/she/CMakeLists.txt
Labels: bugfix, build

#226 Fix dropfile event
  src/she/sdl2/she.cpp
Labels: bugfix

#229 Allow transferring large amounts of data into/from scripts
  src/script/duktape/engine.cpp
  src/script/value.h
Labels: enhancement, scripting, feature

#239 Enable wholearchive flag
  src/CMakeLists.txt
  src/app/script/script_menu.cpp
Labels: scripting, bugfix, OS: Windows

#244 Add support for Lua scripts
  .github/workflows/cmake.yml
  CMakeLists.txt
  INSTALL.md
  data/scripts/Random.lua
  src/app/CMakeLists.txt
  src/app/script/api/app_script.cpp
  src/script/CMakeLists.txt
  src/script/lua/engine.cpp
Labels: scripting, feature

#243 Allow running JavaScript using V8 instead of Duktape
  .github/workflows/cmake.yml
  CMakeLists.txt
  INSTALL.md
  cmake/FindV8.cmake
  src/app/CMakeLists.txt
  src/script/CMakeLists.txt
  src/script/v8/engine.cpp
Labels: scripting, feature

#251 Warn about scripts being an experimental feature
  data/gui.xml
Labels: enhancement, scripting

#252 Clean-up Palette List code, part 2
  src/app/res/palette_resource.h
  src/app/res/palettes_loader_delegate.cpp
  src/app/res/palettes_loader_delegate.h
  src/app/res/resource.h
  src/app/res/resources_loader.cpp
  src/app/res/resources_loader.h
  src/app/task_manager.h
  src/app/ui/palette_listbox.cpp
  src/app/ui/palette_listbox.h
  src/app/ui/palette_popup.cpp
Labels: code quality

#255 Fix sdl2 line bugs
  src/app/ui/editor/editor.cpp
  src/she/sdl2/sdl2_display.cpp
  src/she/sdl2/sdl2_surface.cpp
Labels: bugfix

#250 Documentation issue template
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.md
Labels: documentation

#256 Make devconsole work with multiple scripting engines
  src/app/script/app_scripting.cpp
  src/app/ui/devconsole_view.cpp
  src/app/ui/devconsole_view.h
  src/script/duktape/engine.cpp
  src/script/engine.h
  src/script/lua/engine.cpp
  src/script/v8/engine.cpp
Labels: enhancement, scripting

#257 Fix links
  data/gui.xml
Labels: bugfix

#264 Improve text input
  data/widgets/paste_text.xml
  src/app/commands/cmd_paste_text.cpp
  src/app/ui/font_popup.cpp
  src/app/ui/skin/skin_theme.cpp
  src/ft/face.h
  src/she/common/freetype_font.cpp
  src/she/common/freetype_font.h
  src/she/common/sprite_sheet_font.h
  src/she/font.h
  src/she/keys.h
  src/she/sdl2/she.cpp
  src/ui/entry.cpp
  src/ui/entry.h
  src/ui/widget.cpp
  src/ui/widget.h
Labels: enhancement, bugfix
