Repository LibreSprite/LibreSprite, pull requests merged in 2021-12, with the labels that each got.

#319 Convert some raw pointers into smart ones
  src/app/app.cpp
  src/app/app.h
  src/app/commands/cmd_about.cpp
  src/app/tools/active_tool.cpp
  src/app/tools/active_tool.h
  src/app/tools/tool.h
  src/app/tools/tool_box.cpp
  src/app/tools/tool_box.h
  src/app/ui/editor/brush_preview.cpp
  src/app/ui/editor/editor.cpp
  src/app/ui/editor/editor.h
  src/app/ui/editor/editor_state.h
  src/app/ui/editor/moving_pixels_state.cpp
  src/app/ui/editor/select_box_state.cpp
  src/app/ui/editor/select_box_state.h
  src/app/ui/editor/standby_state.cpp
  src/app/ui/editor/tool_loop_impl.cpp
  src/ui/grid.cpp
Labels: code quality

#323 Include <memory> in active_tool.h
  src/app/tools/active_tool.h
Labels: bugfix, build

#267 Allow scripts to load/store/fetch data
  data/scripts/examples/http.js
  src/app/CMakeLists.txt
  src/app/res/http.h
  src/app/script/api/storage_script.cpp
Labels: scripting

#311 Add donation links
  README.md
  data/gui.xml
Labels: documentation

#329 Initial theme support
  src/app/ui/font_popup.cpp
  src/app/ui/skin/skin_theme.cpp
  src/app/ui/skin/skin_theme.h
  src/base/fs.h
  src/base/fs_osx.mm
  src/base/fs_unix.h
  src/base/fs_win32.h
Labels: bugfix
